### PR TITLE
Add Filebase to the PSA compliance checker

### PR DESCRIPTION
**Pull request by acejam**
Hi there,

We would like to add Filebase to the IPFS PSA compliance checker. The following `SECRETS` can be used:
- `FILEBASE_API_ENDPOINT`: `https://api.filebase.io/v1/ipfs`
- `FILEBASE_API_TOKEN`: Sign up for a free account at https://filebase.com and follow https://docs.filebase.com/storage-networks/ipfs/ipfs-pinning#re-pinning-existing-ipfs-cids-with-filebase-using-the-ipfs-cli to generate a token. We are also happy to provide a token out of band as well if needed.

### CODE REVIEW

**Review by hacdias — APPROVED** [review]
This is great. The PR looks good to me. I run the test suit locally and all tests are successful.

@lidel @SgtPooki I don't have authorization to add secrets to the repository so one of you needs to check this.

**Comment by SgtPooki** [comment]
Secrets added. I'll see about granting you permissions as well @hacdias

**Comment by hacdias** [comment]
@acejam can you please rebase / merge with main to get all upstream fixes and updates?

**Comment by acejam** [comment]
@hacdias Done

**Comment by hacdias** [comment]
@SgtPooki I'm almost sure the failing tests are because the PRs don't have access to the secrets, right? How do we go in situations like this?

**Comment by SgtPooki** [comment]
I kicked off the action manually for a new branch I created from this PR `filebase-addition`: https://github.com/ipfs-shipyard/pinning-service-compliance/actions/runs/2950538940

**Comment by acejam** [comment]
@SgtPooki Thanks for merging! It looks like https://github.com/ipfs-shipyard/pinning-service-compliance/tree/gh-pages is still missing Filebase reports. Did I miss something in this PR?

**Comment by SgtPooki** [comment]
@acejam It's showing properly at https://ipfs-shipyard.github.io/pinning-service-compliance/api.filebase.io.html

**Comment by acejam** [comment]
@SgtPooki Yes, it is now, thanks to ff39295f0a08494758f81a82065e9e232a727284 👍

**Pull request merged**
